[build]
  # This tells Netlify how to compile your Flutter app
  command = "flutter build web --release --dart-define=SUPABASE_URL=$SUPABASE_URL --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY --dart-define=STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY"
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "stable"

[[redirects]]
  # This fixes the "404 error" when you refresh the page in a Flutter Web app
  from = "/*"
  to = "/index.html"
  status = 200